<?php
/**
 * Created by PhpStorm.
 * User: Michael.Crawford
 * Date: 7/8/2016
 * Time: 1:17 PM
 */

namespace Api\Controller;


use Zend\Mvc\Controller\AbstractRestfulController;
use Zend\View\Model\JsonModel;

class ScheduleController extends AbstractRestfulController
{

    public function get($id){
        return new JsonModel([$id]);
    }

    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }

}